packageExtensions:
  "@atls-ui-parts/layout@*":
    dependencies:
      csstype: "*"
  "@atls/webpack-proto-imports-loader@*":
    peerDependencies:
      webpack: ^4.0.0 || ^5.0.0
  "@fragments/landing-main@*":
    peerDependencies:
      next: "*"
  "@landing/index-page@*":
    peerDependencies:
      next: "*"
      react-intl: "*"
  "@landing/state-action-page@*":
    peerDependencies:
      react-intl: "*"
  "@ui/link@*":
    peerDependencies:
      next: "*"

yarnPath: .yarn/releases/yarn-3.5.0.cjs
